import { readFileSync, writeFileSync } from "node:fs";

const version = readFileSync("moon.mod", "utf-8").match(
	/version\s*=\s*"([^"]+)"/,
)?.[1];

if (!version) throw new Error("Version not found in moon.mod");

writeFileSync(
	"src/includes.mbt",
	`// This file is generated by the build process and should not be modified manually.\n\n${(
		[
			["docs/scripts/main.js", "book_scripts_main_js"],
			["docs/styles/index.css", "book_styles_index_css"],
			["docs/templates/default.html", "book_templates_default_html"],
			["docs/demo-book/404.md", "book_404_md"],
			["docs/demo-book/index.md", "book_index_md"],
			["docs/demo-book/SUMMARY.md", "book_summary_md"],
			[
				"docs/plugins/preprocessers/github-alert.ts",
				"book_plugins_preprocessers_github_alert_ts",
			],
			["docs/demo-site/index.md", "site_index_md"],
			["docs/demo-site/about.md", "site_about_md"],
			["docs/demo-site/contact.md", "site_contact_md"],
			["docs/demo-site/site.mbtx", "site_site_mbtx"],
			["docs/demo-site/templates/default.html", "site_templates_default_html"],
			["docs/demo-site/styles/default.css", "site_styles_default_css"],
		] as [string, string][]
	)
		.map(
			([p, n]) =>
				`///|\nlet ${n} : String =\n${readFileSync(p, "utf-8")
					.split("\n")
					.map((l) => `  #|${l}`)
					.join("\n")}\n`,
		)
		.join(
			"\n",
		)}\n///|\npub let version : String = "${version}"\n\n///|\nlet build_time : String = "${new Date().toLocaleString()}"\n`,
);
