import { readFileSync, writeFileSync } from "node:fs";

writeFileSync(
	"src/main/includes.mbt",
	`// This file is generated by the build process and should not be modified manually.\n\n${(
		[
			["docs/scripts/main.js", "scripts_main_js"],
			["docs/styles/index.css", "styles_index_css"],
			["docs/templates/default.html", "templates_default_html"],
			[
				"docs/plugins/preprocessers/github-alert.ts",
				"plugins_preprocessers_github_alert_ts",
			],
		] as [string, string][]
	)
		.map(
			([p, n]) =>
				`///|\nlet ${n} : String =\n${readFileSync(p, "utf-8")
					.split("\n")
					.map((l) => `  #|${l}`)
					.join("\n")}\n`,
		)
		.join("\n")}`,
);
