title = "MoPress Doc"
description = "A modern documentation and static site generator for the MoonBit ecosystem, inspired by mdBook and Hakyll"
keywords = "Documentation,Static Site Generator,SSG,MoonBit,MoonLang,Moon,Functional,Haskell,mdBook,Hakyll"
favicon = "https://himeno-sena.com/favicon.ico"
logo = "https://himeno-sena.com/favicon.ico"
authors = ["Himeno Sena"]
language = "zh"
repository = "https://github.com/biyuehu/mopress"
src = "./"
dest = "./dest"
base-url = "/"

[features]
highlight-enabled = true
highlight-theme = "github"
mathjax-enabled = true

[extensions]
template = "templates/default.html"
assets = [
  "images/**/",
  "styles/**/*",
  "scripts/**/*",
  "plugins/runtime/**/*",
  "index.html",
  "plugins.json",
]
inject-head = []
inject-body = []
use-js = ["console.log('Hello, MoPress!');"]
use-css = []
import-css = []
import-js = ["/plugins/runtime/bili-video.js"]
preprocessors = [
  "bun plugins/preprocessers/github-alert",
  "bun plugins/preprocessers/refer-file",
]
transformers = [
  "bun plugins/transformers/link-checker",
  "bun plugins/transformers/relative2absolute.ts",
]
