name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Moonbit
        uses: hustcer/setup-moonbit@v1

      - name: Update Moonbit registry
        run: moon update

      - name: Run prebuild
        run: just prebuild

      - name: Run checks and tests
        run: |
          moon check
          moon test
          moon info && git diff --exit-code
          moon fmt && git diff --exit-code

      - name: Build project
        run: moon build
